package com.example.zhaojing5.myapplication.bean.databasebean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.zhaojing5.myapplication.bean.databasebean.PersionInfo;

import com.example.zhaojing5.myapplication.bean.databasebean.PersionInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig persionInfoDaoConfig;

    private final PersionInfoDao persionInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        persionInfoDaoConfig = daoConfigMap.get(PersionInfoDao.class).clone();
        persionInfoDaoConfig.initIdentityScope(type);

        persionInfoDao = new PersionInfoDao(persionInfoDaoConfig, this);

        registerDao(PersionInfo.class, persionInfoDao);
    }
    
    public void clear() {
        persionInfoDaoConfig.clearIdentityScope();
    }

    public PersionInfoDao getPersionInfoDao() {
        return persionInfoDao;
    }

}
